#ifndef CUTILS_COMMON_H
#define CUTILS_COMMON_H

typedef enum _CUTILS_REALLOC_ERROR {
    _REALLOC_ERROR = -1,
    _REALLOC_CHANGED = 0,
    _REALLOC_NO_CHANGE = 1
} _CUTILS_REALLOC_ERROR;

#endif // CUTILS_COMMON_H